### ISSUE TITLE
Update bug tracking link in geoapi.org website

### ISSUE THREAD

**Issue by ceefour** [opengeospatial/geoapi#7]
Website still links to non-existing JIRA Codehaus page:

* http://www.geoapi.org/ -> "JIRA task tracker"
* http://www.geoapi.org/issue-tracking.html

It should be changed to link to https://github.com/opengeospatial/geoapi/issues, or the currently used bug tracking.

**Comment by desruisseaux** [comment]
Thanks for reporting. All links to http://jira.codehaus.org/browse/GEO have been replaced (maybe temporarily) by links to https://osgeo-org.atlassian.net/projects/GEO/issues. The later has been kindly provided by OSGeo as a way to save the existing issues. But this may be a temporary move, since we may also use the OGC issue tracker or the GitHub one. We will need to make a survey of what peoples prefer.
