### ISSUE TITLE
Switch from javax.measure:jsr-275 0.9.3 to JSR-363

### ISSUE THREAD

**Issue by ceefour** [opengeospatial/geoapi#8]
geoapi currently uses javax.measure:jsr-275 0.9.3. The latest version of javax.measure:jsr-275 is 1.0 released in 2010.

Please consider switching to jscience 4.3.1, released in 2012.

**Comment by desruisseaux** [comment]
Actually JSR-275 had a tortuous history, until it became rejected by the JCP process. The deployment of JSR-275 version 1.0 on Maven Central is an accident, and that JAR file is actually empty. So we have to ignore it.

JSR-275 is intended to be replaced by JSR-363 (https://jcp.org/en/jsr/detail?id=363), which is a similar API but as interfaces rather than an implementation. JScience would be hopefully one implementation among others, but at developer's choice.

My proposal would be to wait for JSR-363 completion, then switch to that JSR when ready. What do you think?

For the record, the JIRA task for this issue is https://osgeo-org.atlassian.net/projects/GEO/issues/GEO-190

**Comment by ceefour** [comment]
Tag @keilw I'm quite he wants geoapi to switch to JSR363 as well. But probably for 3.1 or 4.0?

**Comment by desruisseaux** [comment]
Yes, I was thinking to propose switching to JSR-363 for GeoAPI 4.0. For GeoAPI 3.1, I'm not sure. This is an open question that I would like to submit to the OGC's SWG or to other communities.

**Comment by keilw** [comment]
We (@leomrlima, @otaviojava and myself) will meet around DevoXX UK for this month's JCP EC F2F. From a recent call where we discussed Collaboration with other Standards-Setting Organizations (see https://java.net/jira/browse/JSR358-37) the PMO is aware of a somewhat "dodgy" situation having one standard GeoAPI refer to another non-final (cancelled or at least archived) one like JSR-275. If Oracle and the PMO thinks it's acceptable for GeoAPI 3.1 to stay as is, I see no need to switch before 4.0, otherwise we'll hear more in London.

**Comment by puntogil** [comment]
Seem NOT free https://github.com/geotools/geotools/wiki/Replace-JSR-275-Units-Library

**Comment by desruisseaux** [comment]
Right, there is licensing issue while JSR-363 is in development. I think the issue will be resolved before JSR-363 goes final. GeoAPI and Apache SIS could use JSR-363 at that point.

**Comment by keilw** [comment]
There are at least 2 JSRs like 107 https://github.com/jsr107/jsr107spec (also with JCP controlling Oracle as co-Spec Lead) or 354 https://github.com/JavaMoney/jsr354-api that went final with the Spec License effectively applied to not only the Spec Document but also API.

Other JSRs still in progress like (also Oracle led) 375 https://github.com/javaee-security-spec/spec-api follow a different pattern so their "api" including what may go to MavenCentral or similar repositories shows the RI/TCK license(s) and only in the written Spec document the spec license is quoted. 

As mentioned in the Wiki, the versoin of JSR-275 used by GeoAPI 3 has always applied the "Spec License" pattern, so effectively you used the Spec License all those years (from what I read it as a non legal expert, "Evaluation" may only be allowed for a certain amount of time, so with the JSR never been final, that could indeed mean, GeoAPI 3 and its implementations violate license terms by Sun/Oracle right now ;-) ) JSR-354 got it correct (unlike 107) so they have both versions of the Spec License, evaluation and implemenmtation: https://github.com/JavaMoney/jsr354-api/blob/master/IMPLEMENTATION-LICENCE.txt

Which if the API repository was to keep it also took its place as soon as JSR-363 goes final.
Since there are other examples even by Oracle as a Spec Lead, we created a JIRA ticket https://java.net/jira/browse/UNITSOFMEASUREMENT-156 to consider changing it in the same way they do it. Having heard about issues by Eclipse in a case where a project (or several, most of them use JScience 4 or a similar version of JSR-275 now, too) wanted to use JSR-363 already.

The GeoTools driven LocationTech however even uses a much older version of JSR-275. Under a "net.java.dev..." groupID, dated long before even its EDR. Eclipse LocationTech projects like uDig use this different/older version of JSR-275 right now, and only OSGi isolating bundles from each other is likely why they face no "Classpath Hell" issue by using 2 not fully compatible versions of JSR-275 in one and the same product;-O

Driven by popular demand, not just at Eclipse we aim to offer a resolution that won't violate "Minimal Requirements" of the JCP, but follows the "freedom of interpretation" as to which license you may use for any kind of software artifacts, not just implementations, but also "API".

**Comment by keilw** [comment]
P.s.: While the license for API or other software artifacts has room for interpretation, that of the GeoAPI Specification http://www.opengeospatial.org/standards/geoapi directly referring to JSR-275 (or later if JSR-363 was used then) also has a very distincive "Spec License" which reads nearly identical to that by Oracle or others. Hence for the written document the Spec License of JSR-275, 363 or any other (except for 2 or so JSRs by Red Hat who negotiated to license everything under Apache) always applies.

**Comment by desruisseaux** [comment]
JSR-363 has been approved as an official JCP standard (https://jcp.org/en/jsr/results?id=5877). This issue is renamed as a switch to JSR-363 instead than JScience. We will start the process at OGC (it may take about two months since we need to go through a vote process and update the GeoAPI 3.0.0 standard).

**Comment by desruisseaux** [comment]
A tag for GeoAPI 3.0.1 using JSR-363 has been created. We will test with at least on GeoAPI implementation before proposing that candidate for a release.

**Comment by desruisseaux** [comment]
Replaced the 3.0.1 tag by a 3.0.x branch. The tag was a little bit premature.

**Comment by desruisseaux** [comment]
Replacement of JSR-275 dependency by JSR-363 has been applied on 3.1-SNAPSHOT (a branch) and 4.0-SNAPSHOT (master) too. We need to update and test at least one GeoAPI implementation before to close this issue.

**Comment by desruisseaux** [comment]
GeoAPI 3.0.1 has been released in September 2017.
